### ISSUE TITLE
Dynamic IDs for accessibility

### ISSUE THREAD

**Issue by slafleche** [vanilla/ebi#27]
Some aria parameters require IDs. A few examples include: `aria-controls` and `aria-labelledby`. It would be nice to have a way to generate dynamic ids... 

If there was a way to say you want dynamic ids for an element and then you can concatenate a suffix for child elements.

An example would be a drop down. You generate an ID for the dropdown, say `dropDown1`, then the button will get `id="dropdown1-handle" aria-controls="dropDown1-content"` and the drop down content will get `id="dropDown1-content" aria-labelledby="dropdown1-handle"`

**Comment by tburry** [comment]
Here are some ideas.

I can see adding an `id()` function that keeps track of IDs so you'd to the following:

```html
<x x-with="id('dropDown')" x-as="id">
    <button id="{id~'-handle'}" aria-controls="{id~'-content'}">Click Me</button>
   <div id="{id~'-content}" aria-labelledby="{id~'-handle'}">...</div>
</x>
```

Let's also consider a helper function `idGroup()` that would take an ID and then return a special object that could handle suffixes. So the above example could look like the following:

```html
<x x-with="idGroup('dropDown')" x-as="id">
    <button id="id.handle" aria-controls="id.content">Click Me</button>
   <div id="id.content" aria-labelledby="id.handle">...</div>
</x>
```

**Comment by slafleche** [comment]
That sounds great! idGroup would also allow to pass the prefix into sub components (if we ever want to pass the id deeper)
