### ISSUE TITLE
Fallback component for x-include

### ISSUE THREAD

**Issue by slafleche** [vanilla/ebi#29]
It would be nice to be able to set a fallback component for x-include. I'm working on the table right now and I have yet to make the component for each cell and I'd like to fallback to a plain text output. This would also be useful if a page was configured to use a plugin but the plugin's broken or missing.

**Comment by tburry** [comment]
You can do this with an expression:

```xml
<x x-inculde="componentExists('component') ? 'component' : 'default'" />
```
